### PR TITLE
Bump to 0.4.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
@takumakanari 

I'll follow these release steps.
https://github.com/embulk/embulk-parser-json#for-maintainers

And release using GitHub Actions.
https://github.com/embulk/embulk-parser-json/blob/main/.github/workflows/publish.yml

I'm studying it. :smile:

### CODE REVIEW

**Comment by chikamura** [comment]
@takumakanari @hiroyuki-sato 
Excuse me, when is it scheduled to be released?
I apologize if you're currenty trying to deal with this. 🙇

**Comment by hiroyuki-sato** [comment]
@chikamura Sorry release late. I'm trying automatic release with GitHub Action.
It will still take a few days. I'll release the gem at first.

@takumakanari Please take a look #39. After merging this PR. close this PR without a merge.

**Comment by hiroyuki-sato** [comment]
@chikamura Released https://rubygems.org/gems/embulk-parser-jsonpath/versions/0.4.1-java Thank you for waiting.

**Comment by chikamura** [comment]
Many thanks!

**Pull request closed without merging**
