### PR TITLE
Fixed documentation and example config (using schema instead of columns)

### PR DESCRIPTION
**Pull request by adolnik**
According to the code the field name should be "schema". Fixed documentation

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
Hello, @adolnik. Thank you for creating this PR.

`schema` is a deprecated option. It outputs the following message. `columns` is correct.

```
Please use 'columns' option instead of 'schema' because the 'schema' option is deprecated. The next version will stop 'schema' option support.
```

**Comment by adolnik** [comment]
Hi @hiroyuki-sato !
I use the Embulk version v0.9.24 with the latest plugin version
If I use **columns** instead of **schema** I've got the following error:
_Error: Required field "schema" is not set_

**Comment by hiroyuki-sato** [comment]
Hello, @adolnik. 

Could you show me your configuration and log file?

The `columns` option works in this example.
https://github.com/hiroyuki-sato/embulk-parser-jsonpath/tree/master/example

```yaml
in:
  type: file
  path_prefix: example/input
  parser:
    type: jsonpath
    root: "$.results"
    default_timezone: "Asia/Tokyo"
    columns:
      - { name: "name",          type: string }
      - { name: "city",          type: string }
      - { name: "street_name",   type: string }
      - { name: "zip_code",      type: string }
      - { name: "registered_at", type: timestamp, format: "%Y-%m-%d %H:%M:%S" }
      - { name: "vegetarian",    type: boolean }
      - { name: "age",           type: long }
      - { name: "ratio",         type: double }
out:
  type: stdout
```

**Comment by adolnik** [comment]
Solved. There was a conflict with **embulk-parser-json** plugin

**Pull request closed without merging**
